name:                todo-haskell
version:             0.1.0.0
github:              "drewboardman/todo_haskell"
license:             BSD3
author:              "Drew Boardman"
maintainer:          "drew.e.boardman@gmail.com"
copyright:           "2019 Drew Boardman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            A simple todo app
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/todo-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- uuid
- text
- time
- hspec
- containers
- beam-core
- beam-sqlite
- aeson
- containers
- free
- sqlite-simple
- scotty
- warp
- servant-server
- aeson
- wai-logger
- lens
- mtl
- monad-logger

library:
  source-dirs:
    - src
    - src/dao
    - src/controllers
    - lib

executables:
  todo-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - todo-haskell

tests:
  todo-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wmissing-import-lists
    - -Wmissing-export-lists
    - -Wincomplete-record-updates
    dependencies:
    - todo-haskell
